# Generated by Django 4.1.4 on 2023-03-25 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile_no",
            field=models.BigIntegerField(
                validators=[django.core.validators.MaxValueValidator(11)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("restaurant", "Restaurant"),
                    ("admin", "Admin"),
                    ("delivery", "Delivery"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
