# Generated by Django 4.1.4 on 2023-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_address_is_selected_alter_contact_is_selected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="mobile_no",
            field=models.CharField(max_length=10),
        ),
    ]
