# Generated by Django 4.1.4 on 2023-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contact_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zipcode",
            field=models.CharField(default="395006", max_length=6),
        ),
    ]
