RESTAURANT_PERMISSION = "please! add restaurant"
RESTRICT_RESTAURANT = "restaurant owner can not be delivery boy so you can not add delivery"
DELIVERY_PERMISSION = "please! add delivery"
RESTRICT_DELIVERY = "delivery boy can not be restaurant manager so you can not add restaurant"
RESTRICT_USER = "user can not be delivery boy OR restaurant owner so you can not add delivery OR restaurant"
RESTRICT_ADMIN = "You can not add admin"
ROLE_PERMISSION = "You can only add role user or restaurant or delivery"
