# Generated by Django 4.1.4 on 2023-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliver_name", models.CharField(max_length=50)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("bike", "Bike"), ("bicycle", "Bicycle")],
                        default="bike",
                        max_length=10,
                    ),
                ),
                ("vehicle_no", models.CharField(default=None, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
