# Generated by Django 4.1.4 on 2023-03-23 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=200)),
                ("owner_email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("open_time", models.TimeField()),
                ("closed_time", models.TimeField()),
                (
                    "holidays",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (1, "Sunday"),
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                            (7, "Saturday"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=7)),
                ("is_approve", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(6)]
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=1000,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default=None, upload_to="images/rest_images/"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
    ]
