# Generated by Django 4.1.4 on 2023-03-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="address",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="city",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="zipcode",
        ),
    ]
