# Generated by Django 4.1.4 on 2023-03-27 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_remove_restaurant_address_remove_restaurant_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="holidays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (1, "Sunday"),
                        (2, "Monday"),
                        (3, "Tuesday"),
                        (4, "Wednesday"),
                        (5, "Thursday"),
                        (6, "Friday"),
                        (7, "Saturday"),
                    ],
                    max_length=10,
                ),
                max_length=3,
                size=None,
            ),
        ),
    ]
