# Generated by Django 4.1.4 on 2023-04-03 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_alter_restaurantimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantimages",
            name="image",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default=None, max_length=200),
                default=None,
                max_length=20,
                size=None,
            ),
        ),
    ]
