# Generated by Django 4.1.4 on 2023-04-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_alter_restaurantimages_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="address",
            new_name="address_id",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="contact",
            new_name="contact_id",
        ),
    ]
