# Generated by Django 4.1.4 on 2023-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.IntegerField(default=None),
        ),
    ]
